name: pytorch with c++ and cuda extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        auto-activate-base: true
        
    - name: Install dependencies
      run: |
        conda install flake8
        conda install --file environment.yml 

    - name: Conda Environment Info
      run: conda info
  
    - name: List Conda Environment
      run: conda list
        
    - name: Build and Test C++ Extension
      run: |
        cd CxxExtension
        pip install .
        python main.py
    