name: pytorch with c++ and cuda extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: myenv
        environment-file: environment.yml
        python-version: "3.10"
        auto-activate-base: false

    - name: Conda Environment Info
      shell: bash -l {0}
      run: conda info
  
    - name: List Conda Environment
      shell: bash -l {0}
      run: conda list
  
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
        pip install flake8
        
    - name: Build and Install C++ Extension
      shell: bash -l {0}
      run: |
        cd CxxExtension
        python setup.py install
        
    - name: Run style check
      shell: bash -l {0}
      run: |
        flake8 main.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 main.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run main.py
      shell: bash -l {0}
      run: |
        python main.py